"""add movie catalog tables

Revision ID: 1e80da06535f
Revises: 3d8ca16fa34c
Create Date: 2026-07-22 19:14:27.739343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e80da06535f'
down_revision: Union[str, None] = '3d8ca16fa34c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('directors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('stars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.Column('imdb', sa.Float(), nullable=False),
    sa.Column('votes', sa.Integer(), nullable=False),
    sa.Column('meta_score', sa.Float(), nullable=True),
    sa.Column('gross', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('certification_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('gross >= 0', name='check_movie_gross_non_negative'),
    sa.CheckConstraint('imdb >= 0 AND imdb <= 10', name='check_movie_imdb_range'),
    sa.CheckConstraint('meta_score >= 0 AND meta_score <= 100', name='check_movie_meta_score_range'),
    sa.CheckConstraint('price >= 0', name='check_movie_price_non_negative'),
    sa.CheckConstraint('time > 0', name='check_movie_time_positive'),
    sa.CheckConstraint('votes >= 0', name='check_movie_votes_non_negative'),
    sa.CheckConstraint('year > 0', name='check_movie_year_positive'),
    sa.ForeignKeyConstraint(['certification_id'], ['certifications.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'year', 'time', name='unique_movie_constraint'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('movie_directors',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('director_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['director_id'], ['directors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movie_id', 'director_id')
    )
    op.create_index(op.f('ix_movie_directors_director_id'), 'movie_directors', ['director_id'], unique=False)
    op.create_index(op.f('ix_movie_directors_movie_id'), 'movie_directors', ['movie_id'], unique=False)
    op.create_table('movie_genres',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movie_id', 'genre_id')
    )
    op.create_index(op.f('ix_movie_genres_genre_id'), 'movie_genres', ['genre_id'], unique=False)
    op.create_index(op.f('ix_movie_genres_movie_id'), 'movie_genres', ['movie_id'], unique=False)
    op.create_table('movie_stars',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('star_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['star_id'], ['stars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movie_id', 'star_id')
    )
    op.create_index(op.f('ix_movie_stars_movie_id'), 'movie_stars', ['movie_id'], unique=False)
    op.create_index(op.f('ix_movie_stars_star_id'), 'movie_stars', ['star_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movie_stars_star_id'), table_name='movie_stars')
    op.drop_index(op.f('ix_movie_stars_movie_id'), table_name='movie_stars')
    op.drop_table('movie_stars')
    op.drop_index(op.f('ix_movie_genres_movie_id'), table_name='movie_genres')
    op.drop_index(op.f('ix_movie_genres_genre_id'), table_name='movie_genres')
    op.drop_table('movie_genres')
    op.drop_index(op.f('ix_movie_directors_movie_id'), table_name='movie_directors')
    op.drop_index(op.f('ix_movie_directors_director_id'), table_name='movie_directors')
    op.drop_table('movie_directors')
    op.drop_table('movies')
    op.drop_table('stars')
    op.drop_table('genres')
    op.drop_table('directors')
    op.drop_table('certifications')
    # ### end Alembic commands ###
