"""remove unique constraint from refresh tokens

Revision ID: 3d8ca16fa34c
Revises: 5be4c52b6ea2
Create Date: 2026-07-09 15:56:02.271233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d8ca16fa34c'
down_revision: Union[str, None] = '5be4c52b6ea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('refresh_tokens_user_id_key', 'refresh_tokens', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('refresh_tokens_user_id_key', 'refresh_tokens', ['user_id'])
    # ### end Alembic commands ###
