"""Fix user profile relationship

Revision ID: 5be4c52b6ea2
Revises: caeb7a97817b
Create Date: 2026-07-08 19:16:19.767651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5be4c52b6ea2'
down_revision: Union[str, None] = 'caeb7a97817b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.drop_column('user_profiles', 'frist_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('frist_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('user_profiles', 'first_name')
    # ### end Alembic commands ###
